name: flagx
channels:
  - pytorch  # todo
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # - python>=3.10,<3.14
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - numba
  - umap-learn
  - anndata
  - scanpy
  - igraph
  - leidenalg
  - fcsparser
  - readfcs
  - pytometry
  - tqdm
  - requests
  - somoclu
  - pytorch=2.2.2  # todo
  - pip

  - pip:
      # - torch==2.2.2 --index-url https://download.pytorch.org/whl/cpu
      # - torch --index-url https://download.pytorch.org/whl/cpu
      - flowio
      - flowutils

