
name: flagx
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python>=3.10,<3.14
  - numpy
  - pandas
  - scanpy
  - umap-learn
  - matplotlib
  - pytometry
  - flowio
  - scikit-learn
  - scipy
  - numba
  - somoclu
  - click
  - pyyaml
  - typing_extensions
  - pip

  - pip:
      - torch --index-url https://download.pytorch.org/whl/cpu

